// <auto-generated />
using System;
using CSharpHerryWijayaMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSharpHerryWijayaMVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250908124011_mvcfix4")]
    partial class mvcfix4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CSharpHerryWijayaMVC.Models.Descendant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Descendant");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Freyna"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Serena"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ines"
                        });
                });

            modelBuilder.Entity("CSharpHerryWijayaMVC.Models.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Inventory");

                    b.HasData(
                        new
                        {
                            Id = 1
                        });
                });

            modelBuilder.Entity("CSharpHerryWijayaMVC.Models.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InventoryId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId");

                    b.HasIndex("ItemId");

                    b.ToTable("InventoryItem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InventoryId = 1,
                            ItemId = 1,
                            Quantity = 200
                        },
                        new
                        {
                            Id = 2,
                            InventoryId = 1,
                            ItemId = 2,
                            Quantity = 200
                        },
                        new
                        {
                            Id = 3,
                            InventoryId = 1,
                            ItemId = 3,
                            Quantity = 200
                        },
                        new
                        {
                            Id = 4,
                            InventoryId = 1,
                            ItemId = 4,
                            Quantity = 200
                        },
                        new
                        {
                            Id = 5,
                            InventoryId = 1,
                            ItemId = 5,
                            Quantity = 200
                        },
                        new
                        {
                            Id = 6,
                            InventoryId = 1,
                            ItemId = 6,
                            Quantity = 200
                        },
                        new
                        {
                            Id = 7,
                            InventoryId = 1,
                            ItemId = 7,
                            Quantity = 200
                        });
                });

            modelBuilder.Entity("CSharpHerryWijayaMVC.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Murky Energy Residue"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mixed Energy Residue"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Macromolecule Biogel"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Advanced Neural Circuit"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Crystallization Catalyst Blueprint"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Superalloy"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Liquid Metal"
                        },
                        new
                        {
                            Id = 8,
                            Name = "High Precision Exchange Components"
                        });
                });

            modelBuilder.Entity("CSharpHerryWijayaMVC.Models.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DescendantId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModuleCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DescendantId");

                    b.HasIndex("ModuleCategoryId");

                    b.ToTable("Module");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "DEF +166.80%, Max Shield -36.50%",
                            ModuleCategoryId = 2,
                            Name = "Shield Conversion (DEF)"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Toxic Skill Power +81.20%",
                            ModuleCategoryId = 3,
                            Name = "Toxic Specialist"
                        },
                        new
                        {
                            Id = 3,
                            Description = "All Attribute Resistances +640.80",
                            ModuleCategoryId = 1,
                            Name = "Polygenic Antibody"
                        },
                        new
                        {
                            Id = 4,
                            Description = "When Shield is at 0%, DEF +128.30%",
                            ModuleCategoryId = 4,
                            Name = "An Iron Will"
                        },
                        new
                        {
                            Id = 5,
                            DescendantId = 1,
                            Description = "When an enemy inflicted with Room 0 Trauma is killed, a contagion of Room 0 Trauma surrounds it.",
                            ModuleCategoryId = 5,
                            Name = "Contagion"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Skill Speed & Range Increase Modifier +19.20%",
                            ModuleCategoryId = 1,
                            Name = "Arche Acceleration"
                        });
                });

            modelBuilder.Entity("CSharpHerryWijayaMVC.Models.ModuleCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ModuleCategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "None"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Defense"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Battle"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Support Tech"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Transcendent"
                        });
                });

            modelBuilder.Entity("CSharpHerryWijayaMVC.Models.ModuleDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<int>("ModuleStatsId")
                        .HasColumnType("int");

                    b.Property<double>("ValueModifier")
                        .HasColumnType("float");

                    b.Property<string>("ValueModifierType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("ModuleStatsId");

                    b.ToTable("ModuleDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ModuleId = 1,
                            ModuleStatsId = 1,
                            ValueModifier = 166.80000000000001,
                            ValueModifierType = "percentage"
                        },
                        new
                        {
                            Id = 2,
                            ModuleId = 1,
                            ModuleStatsId = 6,
                            ValueModifier = -36.5,
                            ValueModifierType = "percentage"
                        },
                        new
                        {
                            Id = 3,
                            ModuleId = 2,
                            ModuleStatsId = 3,
                            ValueModifier = 81.200000000000003,
                            ValueModifierType = "percentage"
                        },
                        new
                        {
                            Id = 4,
                            ModuleId = 3,
                            ModuleStatsId = 4,
                            ValueModifier = 640.79999999999995,
                            ValueModifierType = "raw"
                        },
                        new
                        {
                            Id = 5,
                            ModuleId = 4,
                            ModuleStatsId = 5,
                            ValueModifier = 0.0,
                            ValueModifierType = "situational"
                        },
                        new
                        {
                            Id = 6,
                            ModuleId = 5,
                            ModuleStatsId = 5,
                            ValueModifier = 0.0,
                            ValueModifierType = "situational"
                        },
                        new
                        {
                            Id = 7,
                            ModuleId = 6,
                            ModuleStatsId = 2,
                            ValueModifier = 19.199999999999999,
                            ValueModifierType = "percentage"
                        });
                });

            modelBuilder.Entity("CSharpHerryWijayaMVC.Models.ModuleStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ModuleStats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "DEF"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Skill Effect Range"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Toxic Skill Power"
                        },
                        new
                        {
                            Id = 4,
                            Name = "All Attribute Resistances"
                        },
                        new
                        {
                            Id = 5,
                            Name = "-"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Max Shield"
                        });
                });

            modelBuilder.Entity("CSharpHerryWijayaMVC.Models.Research", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Research");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Duration = new TimeSpan(0, 0, 1, 40, 0),
                            Name = "Crystallization Catalyst"
                        },
                        new
                        {
                            Id = 2,
                            Duration = new TimeSpan(0, 0, 0, 10, 0),
                            Name = "Phase Exchanger"
                        },
                        new
                        {
                            Id = 3,
                            Duration = new TimeSpan(0, 0, 0, 40, 0),
                            Name = "Precision Phase Exchanger"
                        },
                        new
                        {
                            Id = 4,
                            Duration = new TimeSpan(0, 0, 0, 40, 0),
                            Name = "Precision Phase Exchanger"
                        });
                });

            modelBuilder.Entity("CSharpHerryWijayaMVC.Models.ResearchRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ResearchId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("ResearchId");

                    b.ToTable("ResearchRequirement");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ItemId = 1,
                            Quantity = 8,
                            ResearchId = 1
                        },
                        new
                        {
                            Id = 2,
                            ItemId = 2,
                            Quantity = 8,
                            ResearchId = 1
                        },
                        new
                        {
                            Id = 3,
                            ItemId = 3,
                            Quantity = 22,
                            ResearchId = 1
                        },
                        new
                        {
                            Id = 4,
                            ItemId = 4,
                            Quantity = 18,
                            ResearchId = 1
                        },
                        new
                        {
                            Id = 5,
                            ItemId = 5,
                            Quantity = 1,
                            ResearchId = 1
                        },
                        new
                        {
                            Id = 6,
                            ItemId = 6,
                            Quantity = 50,
                            ResearchId = 2
                        },
                        new
                        {
                            Id = 7,
                            ItemId = 7,
                            Quantity = 250,
                            ResearchId = 3
                        },
                        new
                        {
                            Id = 8,
                            ItemId = 8,
                            Quantity = 250,
                            ResearchId = 4
                        });
                });

            modelBuilder.Entity("CSharpHerryWijayaMVC.Models.InventoryItem", b =>
                {
                    b.HasOne("CSharpHerryWijayaMVC.Models.Inventory", "Inventory")
                        .WithMany("Items")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSharpHerryWijayaMVC.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("CSharpHerryWijayaMVC.Models.Module", b =>
                {
                    b.HasOne("CSharpHerryWijayaMVC.Models.Descendant", "Descendant")
                        .WithMany()
                        .HasForeignKey("DescendantId");

                    b.HasOne("CSharpHerryWijayaMVC.Models.ModuleCategory", "ModuleCategory")
                        .WithMany()
                        .HasForeignKey("ModuleCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Descendant");

                    b.Navigation("ModuleCategory");
                });

            modelBuilder.Entity("CSharpHerryWijayaMVC.Models.ModuleDetails", b =>
                {
                    b.HasOne("CSharpHerryWijayaMVC.Models.Module", "Module")
                        .WithMany("Details")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSharpHerryWijayaMVC.Models.ModuleStats", "ModuleStats")
                        .WithMany()
                        .HasForeignKey("ModuleStatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("ModuleStats");
                });

            modelBuilder.Entity("CSharpHerryWijayaMVC.Models.ResearchRequirement", b =>
                {
                    b.HasOne("CSharpHerryWijayaMVC.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSharpHerryWijayaMVC.Models.Research", "Research")
                        .WithMany("Requirements")
                        .HasForeignKey("ResearchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Research");
                });

            modelBuilder.Entity("CSharpHerryWijayaMVC.Models.Inventory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CSharpHerryWijayaMVC.Models.Module", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("CSharpHerryWijayaMVC.Models.Research", b =>
                {
                    b.Navigation("Requirements");
                });
#pragma warning restore 612, 618
        }
    }
}
