// <auto-generated />
using System;
using CSharpHerryWijayaMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSharpHerryWijayaMVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CSharpHerryWijayaMVC.Models.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Inventory");

                    b.HasData(
                        new
                        {
                            Id = 1
                        });
                });

            modelBuilder.Entity("CSharpHerryWijayaMVC.Models.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InventoryId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId");

                    b.HasIndex("ItemId");

                    b.ToTable("InventoryItem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InventoryId = 1,
                            ItemId = 1,
                            Quantity = 200
                        },
                        new
                        {
                            Id = 2,
                            InventoryId = 1,
                            ItemId = 2,
                            Quantity = 200
                        },
                        new
                        {
                            Id = 3,
                            InventoryId = 1,
                            ItemId = 3,
                            Quantity = 200
                        },
                        new
                        {
                            Id = 4,
                            InventoryId = 1,
                            ItemId = 4,
                            Quantity = 200
                        },
                        new
                        {
                            Id = 5,
                            InventoryId = 1,
                            ItemId = 5,
                            Quantity = 200
                        },
                        new
                        {
                            Id = 6,
                            InventoryId = 1,
                            ItemId = 6,
                            Quantity = 200
                        },
                        new
                        {
                            Id = 7,
                            InventoryId = 1,
                            ItemId = 7,
                            Quantity = 200
                        });
                });

            modelBuilder.Entity("CSharpHerryWijayaMVC.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Murky Energy Residue"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mixed Energy Residue"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Macromolecule Biogel"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Advanced Neural Circuit"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Crystallization Catalyst Blueprint"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Superalloy"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Liquid Metal"
                        },
                        new
                        {
                            Id = 8,
                            Name = "High Precision Exchange Components"
                        });
                });

            modelBuilder.Entity("CSharpHerryWijayaMVC.Models.Research", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Research");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Duration = new TimeSpan(0, 0, 1, 40, 0),
                            Name = "Crystallization Catalyst"
                        },
                        new
                        {
                            Id = 2,
                            Duration = new TimeSpan(0, 0, 0, 10, 0),
                            Name = "Phase Exchanger"
                        },
                        new
                        {
                            Id = 3,
                            Duration = new TimeSpan(0, 0, 0, 40, 0),
                            Name = "Precision Phase Exchanger"
                        },
                        new
                        {
                            Id = 4,
                            Duration = new TimeSpan(0, 0, 0, 40, 0),
                            Name = "Precision Phase Exchanger"
                        });
                });

            modelBuilder.Entity("CSharpHerryWijayaMVC.Models.ResearchRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ResearchId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("ResearchId");

                    b.ToTable("ResearchRequirement");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ItemId = 1,
                            Quantity = 8,
                            ResearchId = 1
                        },
                        new
                        {
                            Id = 2,
                            ItemId = 2,
                            Quantity = 8,
                            ResearchId = 1
                        },
                        new
                        {
                            Id = 3,
                            ItemId = 3,
                            Quantity = 22,
                            ResearchId = 1
                        },
                        new
                        {
                            Id = 4,
                            ItemId = 4,
                            Quantity = 18,
                            ResearchId = 1
                        },
                        new
                        {
                            Id = 5,
                            ItemId = 5,
                            Quantity = 1,
                            ResearchId = 1
                        },
                        new
                        {
                            Id = 6,
                            ItemId = 6,
                            Quantity = 50,
                            ResearchId = 2
                        },
                        new
                        {
                            Id = 7,
                            ItemId = 7,
                            Quantity = 250,
                            ResearchId = 3
                        },
                        new
                        {
                            Id = 8,
                            ItemId = 8,
                            Quantity = 250,
                            ResearchId = 4
                        });
                });

            modelBuilder.Entity("CSharpHerryWijayaMVC.Models.InventoryItem", b =>
                {
                    b.HasOne("CSharpHerryWijayaMVC.Models.Inventory", "Inventory")
                        .WithMany("Items")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSharpHerryWijayaMVC.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("CSharpHerryWijayaMVC.Models.ResearchRequirement", b =>
                {
                    b.HasOne("CSharpHerryWijayaMVC.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CSharpHerryWijayaMVC.Models.Research", "Research")
                        .WithMany("Requirements")
                        .HasForeignKey("ResearchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Research");
                });

            modelBuilder.Entity("CSharpHerryWijayaMVC.Models.Inventory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CSharpHerryWijayaMVC.Models.Research", b =>
                {
                    b.Navigation("Requirements");
                });
#pragma warning restore 612, 618
        }
    }
}
